version: "3.7"

services:
  postgres_db:
    container_name: dentzen_postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: "5432"
    volumes:
      - ./main/data/db:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c", "log_statement=all"]

  mongo_db:
    container_name: dentzen_mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: comments
    volumes:
      - ./comments/data/mongo:/data/db
    restart: always
#    command:
#      - su && mkdir /data/db/log && mongod --dbpath data/db --fork --logpath data/db/log && rm /data/db/mongod.lock && mongod

  neo4j:
    image: neo4j:latest
    restart: always
    volumes:
      - ./pr/data/neo4j:/var/lib/neo4j/data
    ports:
      - "7474:7474"
      - "7687:7687"

  app:
    build: ./main
    container_name: dentzen_app
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOSTNAME: postgres_db
    depends_on:
      - postgres_db

  comments:
    build: ./comments
    container_name: dentzen_comments
    volumes:
      - .:/code/
    ports:
      - "9000:9000"
    environment:
      MONGO_USERNAME: mongo
      MONGO_PASSWORD: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo_db

  pr:
    build: ./pr
    container_name: dentzen_pr
    volumes:
      - .:/code/
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      PORT: 3000
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: neo
      NEO4J_PORT: 7687
      NEO4J_HOST: neo4j
      NEO4J_SCHEME: bolt
      NEO4J_DATABASE: neo4j
    depends_on:
      - neo4j
