version: "3.7"

services:
  postgres_db:
    container_name: dentzen_postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: "5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
  
  app:
    build: .
    container_name: dentzen_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOSTNAME: postgres_db
    depends_on:
      - postgres_db
