# Generated by Django 3.2.16 on 2022-12-11 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0002_remove_instrument_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dentzen_app.dentist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dentzen_app.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalclinic',
            name='dentists',
            field=models.ManyToManyField(through='dentzen_app.DentistClinicContract', to='dentzen_app.Dentist'),
        ),
        migrations.AddField(
            model_name='dentistcliniccontract',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dentistcliniccontract',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dentzen_app.disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dentzen_app.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='age_group',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='drug',
            name='supplier',
        ),
        migrations.AddField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dentzen_app.supplier'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='supplier',
        ),
        migrations.AddField(
            model_name='instrument',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dentzen_app.supplier'),
            preserve_default=False,
        ),
    ]
