# Generated by Django 3.2.16 on 2022-12-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0005_alter_dentist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dentist',
            table='dentists',
        ),
    ]
