# Generated by Django 3.2.16 on 2022-12-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0012_auto_20221214_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dentistcliniccontract',
            unique_together={('clinic', 'dentist')},
        ),
        migrations.AlterIndexTogether(
            name='dentistcliniccontract',
            index_together=set(),
        ),
    ]
