# Generated by Django 3.2.16 on 2022-12-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0004_alter_dentist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dentist',
            table='dentist',
        ),
    ]
