# Generated by Django 3.2.16 on 2022-12-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0006_alter_dentist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dentalclinic',
            table='clinics',
        ),
    ]
