# Generated by Django 3.2.16 on 2022-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0007_alter_dentalclinic_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dentistcliniccontract',
            table='dentist_clinic_contract',
        ),
    ]
