# Generated by Django 3.2.16 on 2022-12-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0009_alter_dentistcliniccontract_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalclinic',
            name='dentists',
        ),
    ]
