# Generated by Django 3.2.16 on 2022-12-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentzen_app', '0011_dentalclinic_dentists'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dentistcliniccontract',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='dentistcliniccontract',
            index_together={('clinic', 'dentist')},
        ),
    ]
